### ISSUE TITLE
Clarification on the data model Case

### ISSUE THREAD

**Issue by silemi5** [covid19zc/covid19zc-backend#2]
On the data model `Case`, I need some clarifications regarding their attributes.

Below is the relevant data model which were already been defined [here](https://github.com/covid19zc/covid19zc-backend/blob/master/api/cases/models/cases.settings.json).

| Attribute | Data type | Required? |
| --- | --- | --- |
| Case ID/Number | String | YES |
| Age | Integer |
| Elderly | Boolean |
| Gender | String | YES |
| Nationality | String |
| Date of Arrival | Date |
| Onset Of Symptoms | Date |
| With Comorbidity | Boolean |
| Previous Conditions | String |
| Current Location | String | YES |
| Exposure | String |
| Symptoms | String |
| Date Result | Date |
| Facility Consultation | String |
| Date of Lab Confirmation | Date |
| Status | String | YES |
| Last Updated | Date |

**Comment by JHNLWHD** [comment]
@silemi5 
- What kind of validation does this issue want to achieve? 
- Is it just checking if a certain attribute is required or not? *If no, please state in the description of this issue.*

**Comment by silemi5** [comment]
> 
> 
> @silemi5
> 
>     * What kind of validation does this issue want to achieve?
> 
>     * Is it just checking if a certain attribute is required or not? _If no, please state in the description of this issue._

- Validation for necessary fields before being put into the system.
- Yes. I have updated the issue description (and also its title) to better clarify this.

**Comment by JHNLWHD** [comment]
The data you've set to required is the data almost all of the media sources published. So, it's best to keep this config in the current state of telling which is a required attribute except for the  `LastUpdated`.

**Suggestion:** Make `LastUpdated` as `required` attribute.

**Comment by jhon-andrew** [comment]
You can use Strapi's default `updated_at` prop instead of defining your own `Last Updated` property. Every data inserted and updated has it, including the `created_at` upon inserting.
